update dependencies for 0.86.0
AnacondaRecipes/cfn-lint-feedstock pull request #17
Opened 2024-03-20 15:09 UTC by JamesRobertsonGames

cfn-lint 0.86.0

**Destination channel:** defaults

### Links

- [PKG-3626](https://anaconda.atlassian.net/browse/PKG-3626) 
- [Upstream repository](https://github.com/aws-cloudformation/cfn-lint)
- [Upstream changelog/diff](https://github.com/aws-cloudformation/cfn-lint/releases/tag/v0.86.0)

### Explanation of changes:

- Inclusion of new packages:  jschema-to-python, aws-sam-translator 1.86.0

2024-03-20 15:19 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_4dxld6g87w/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:39: python_build_tool_in_run: The python build tool setuptools is in run depends

===== ERRORS =====
- clone/recipe/meta.yaml:61: incorrect_license: The recipe's `about/license` key is not an SPDX compliant license or license exception, reference https://spdx.org/licenses/
===== Final Report: =====
1 Error and 1 Warning were found

</details>

2024-03-21 09:48 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_72abi9p5v6/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:39: python_build_tool_in_run: The python build tool setuptools is in run depends
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-03-21 09:51 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_29e0i9u63f/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:40: python_build_tool_in_run: The python build tool setuptools is in run depends

===== ERRORS =====
- clone/recipe/meta.yaml:43: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
- clone/recipe/meta.yaml:31: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
===== Final Report: =====
2 Errors and 1 Warning were found

</details>

2024-03-21 09:58 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_9c_eywpl8o/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:40: python_build_tool_in_run: The python build tool setuptools is in run depends
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-03-21 16:01 UTC, JeanChristopheMorinPerso requested changes

2024-03-21 16:01 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
>    requires:
`junit-xml` and `importlib_resources` should be removed from the test section.

2024-03-25 14:07 UTC, JeanChristopheMorinPerso approved these changes

2024-03-25 14:48 UTC, cbouss approved these changes

2024-03-25 20:45 UTC, merged